// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtI6cKnrvpyJ4XDz6BBDajWlJQiJlL-mI',
    appId: '1:182589418319:web:592ed598440906a6d2333a',
    messagingSenderId: '182589418319',
    projectId: 'qr-scan-120ef',
    authDomain: 'qr-scan-120ef.firebaseapp.com',
    storageBucket: 'qr-scan-120ef.appspot.com',
    measurementId: 'G-VW7YFG7ZTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSyx0EF_mg0xyKLG9BJJHYjrV-cbtozI',
    appId: '1:182589418319:android:8481c3b60fb11261d2333a',
    messagingSenderId: '182589418319',
    projectId: 'qr-scan-120ef',
    storageBucket: 'qr-scan-120ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsD8gvvLlxfOwkYNmTd9jslNgHuPZfga0',
    appId: '1:182589418319:ios:c36985b224334d57d2333a',
    messagingSenderId: '182589418319',
    projectId: 'qr-scan-120ef',
    storageBucket: 'qr-scan-120ef.appspot.com',
    iosClientId: '182589418319-cucmqqbhapgjo5rooai2bvdsgh5cmssf.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsD8gvvLlxfOwkYNmTd9jslNgHuPZfga0',
    appId: '1:182589418319:ios:c36985b224334d57d2333a',
    messagingSenderId: '182589418319',
    projectId: 'qr-scan-120ef',
    storageBucket: 'qr-scan-120ef.appspot.com',
    iosClientId: '182589418319-cucmqqbhapgjo5rooai2bvdsgh5cmssf.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrApp',
  );
}
